import { readdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { parseScore, decodeScore } from "../src/core/xml";
import { createSteps, verifySteps } from "../src/core/notation";
import { secondsAt, type Entry } from "../src/core/model";
const files = (await readdir("public/scores"))
  .filter((f) => /\.(mxl|xml|musicxml)$/i.test(f))
  .sort();
const entries: Entry[] = [];
const hashes = new Map<string, string>();
for (const file of files) {
  const bytes = await readFile(`public/scores/${file}`);
  const hash = createHash("sha256").update(bytes).digest("hex");
  const duplicate = hashes.get(hash);
  hashes.set(hash, file);
  const base: Entry = {
    id: createHash("sha256").update(file).digest("hex").slice(0, 12),
    file: `scores/${file}`,
    arrangement: file.replace(/_/g, " ").replace(/\.[^.]+$/, ""),
    title: file.replace(/_/g, " ").replace(/\.[^.]+$/, ""),
    composer: "",
    difficulty: "Unrated",
    basis:
      "No verified difficulty classification is available for this exact arrangement.",
    status: "error",
    warnings: [],
    source: `https://github.com/musetrainer/library/blob/master/scores/${encodeURIComponent(file)}`,
    rights: [],
    measures: 0,
    notes: 0,
    seconds: 0,
  };
  try {
    const score = parseScore(decodeScore(bytes), { title: base.title });
    const steps = createSteps(score);
    verifySteps(steps);
    base.title = score.title;
    base.composer = score.composer;
    base.source = score.source || base.source;
    base.rights = score.rights;
    base.measures = score.measures.length;
    base.notes = score.notes.length;
    base.seconds = secondsAt(score.end, score);
    base.warnings = score.warnings;
    base.status = score.warnings.length ? "review" : "ready";
    if (/easy|beginner/i.test(file + " " + score.title)) {
      base.difficulty = "Beginner";
      base.basis =
        "Estimated from this arrangement’s “easy”/“beginner” title. Not an independently verified teacher grade.";
      base.difficultySource = base.source;
    }
    // A conservative complexity flag, deliberately not a universal musical grade.
    else if (
      score.notes.length > 2000 ||
      steps.some((s) =>
        ["RH", "LH"].some((h) => {
          const a = s.after[h as "RH" | "LH"];
          return (
            a.length >= 5 ||
            (a.length >= 2 && Math.max(...a) - Math.min(...a) > 16)
          );
        }),
      )
    ) {
      base.difficulty = "Advanced";
      base.basis =
        "Estimated from dense writing or large simultaneous spans. Not an external grade.";
    }
  } catch (e) {
    base.warnings = [e instanceof Error ? e.message : String(e)];
  }
  if (duplicate)
    base.warnings.push(
      `Byte-identical source also exists as ${duplicate}. Kept visible for inventory completeness.`,
    );
  entries.push(base);
}
entries.sort((a, b) => a.title.localeCompare(b.title));
await writeFile("public/catalog.json", JSON.stringify(entries, null, 2));
await writeFile(
  "docs/catalog-inventory.md",
  `# Catalog inventory\n\nGenerated by npm run catalog. All ${files.length} source files are accounted for; no title-only deduplication.\n\nReady means our parser and notation round-trip checks passed, not that a musician has verified hand assignment or performance. Review entries are inspectable but require an explicit preview acknowledgement.\n\nDifficulty: external MuseScore pages for the initial candidates were inaccessible during implementation. “Easy”/“beginner” arrangement titles produce visibly estimated Beginner labels. Dense/large-span arrangements receive visibly estimated Advanced labels; other pieces remain Unrated. No verified intermediate grades were invented.\n\n| Arrangement | State | Difficulty | Reason / provenance |\n|---|---|---|---|\n` +
    entries
      .map(
        (e) =>
          `| ${e.title.replaceAll("|", "/")} | ${e.status} | ${e.difficulty} | ${[...e.warnings, e.basis].join(" ").replaceAll("|", "/")} [source](${e.source}) |`,
      )
      .join("\n") +
    "\n",
);
console.log(
  `${entries.length} pieces: ${entries.filter((e) => e.status === "ready").length} ready, ${entries.filter((e) => e.status === "review").length} review, ${entries.filter((e) => e.status === "error").length} errors`,
);
